        
-- Generated by Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   at:        2023-01-07 17:06:59 EET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE appointment (
    appointment_id NUMBER NOT NULL,
    attendance     VARCHAR2(10),
    volunteer_id   NUMBER NOT NULL,
    requirement_id NUMBER NOT NULL
);

ALTER TABLE appointment
    ADD CONSTRAINT appointment_attendance_ck CHECK ( attendance IN ( 'absent', 'prezent' ) );

ALTER TABLE appointment ADD CONSTRAINT appointment_pk PRIMARY KEY ( appointment_id );

CREATE TABLE department (
    department_id   NUMBER NOT NULL,
    department_name VARCHAR2(20) NOT NULL
);

ALTER TABLE department
    ADD CONSTRAINT department_department_name_ck CHECK ( length(department_name) > 1 );

ALTER TABLE department ADD CONSTRAINT department_pk PRIMARY KEY ( department_id );

ALTER TABLE department ADD CONSTRAINT department_department_name_uk UNIQUE ( department_name );

CREATE TABLE event (
    event_id    NUMBER NOT NULL,
    starttime   TIMESTAMP NOT NULL,
    endtime     TIMESTAMP NOT NULL,
    location_id NUMBER NOT NULL
);

ALTER TABLE event ADD CONSTRAINT event_pk PRIMARY KEY ( event_id );

CREATE TABLE location (
    location_id      NUMBER NOT NULL,
    city             VARCHAR2(20) NOT NULL,
    county           VARCHAR2(20) NOT NULL,
    street           VARCHAR2(30) NOT NULL,
    number_of_street NUMBER NOT NULL
);

ALTER TABLE location
    ADD CONSTRAINT location_city_ck CHECK ( length(city) > 2 );

ALTER TABLE location
    ADD CONSTRAINT location_county_ck CHECK ( length(county) > 2 );

ALTER TABLE location
    ADD CONSTRAINT location_street_ck CHECK ( length(street) > 2 );

ALTER TABLE location ADD CONSTRAINT location_pk PRIMARY KEY ( location_id );

ALTER TABLE location
    ADD CONSTRAINT location_allattributes_uk UNIQUE ( city,
                                                      county,
                                                      street,
                                                      number_of_street );

CREATE TABLE observation (
    observation_id NUMBER NOT NULL,
    message        VARCHAR2(30) NOT NULL,
    appointment_id NUMBER NOT NULL
);

ALTER TABLE observation
    ADD CONSTRAINT observation_message_ck CHECK ( length(message) > 2 );

CREATE UNIQUE INDEX observation__idx ON
    observation (
        appointment_id
    ASC );

ALTER TABLE observation ADD CONSTRAINT comment_pk PRIMARY KEY ( observation_id );

CREATE TABLE requirement (
    requirement_id       NUMBER NOT NULL,
    number_of_volunteers NUMBER NOT NULL,
    event_id             NUMBER NOT NULL,
    department_id        NUMBER NOT NULL
);

ALTER TABLE requirement ADD CONSTRAINT requirement_number_ck CHECK ( number_of_volunteers > 0 );

ALTER TABLE requirement ADD CONSTRAINT requirement_pk PRIMARY KEY ( requirement_id );

CREATE TABLE volunteer (
    volunteer_id  NUMBER NOT NULL,
    last_name     VARCHAR2(20) NOT NULL,
    first_name    VARCHAR2(20) NOT NULL,
    faculty       VARCHAR2(30),
    email         VARCHAR2(30) NOT NULL,
    phone_number  VARCHAR2(15) NOT NULL,
    city          VARCHAR2(20),
    department_id NUMBER NOT NULL
);

ALTER TABLE volunteer
    ADD CONSTRAINT volunteer_last_name_ck CHECK ( REGEXP_LIKE ( last_name,
                                                                '^[a-zA-Z]+$' )
                                                  AND length(last_name) > 2 );

ALTER TABLE volunteer
    ADD CONSTRAINT volunteer_first_name_ck CHECK ( REGEXP_LIKE ( first_name,
                                                                 '^[a-zA-Z]+$' )
                                                   AND length(first_name) > 2 );

ALTER TABLE volunteer
    ADD CONSTRAINT volunteer_faculty_ck CHECK ( REGEXP_LIKE ( faculty,
                                                              '^[a-zA-Z]+$' )
                                                AND length(faculty) > 1 );

ALTER TABLE volunteer
    ADD CONSTRAINT volunteer_email_ck CHECK ( REGEXP_LIKE ( email,
                                                            '[a-z0-9._%-]+@[a-z0-9._%-]+\.[a-z]{2,4}' ) );

ALTER TABLE volunteer
    ADD CONSTRAINT volunteer_phone_ck CHECK ( REGEXP_LIKE ( phone_number,
                                                            '^[0-9]+$' ) );

ALTER TABLE volunteer
    ADD CONSTRAINT volunteer_city_ck CHECK ( length(city) > 2 );

ALTER TABLE volunteer ADD CONSTRAINT volunteer_pk PRIMARY KEY ( volunteer_id );

ALTER TABLE volunteer ADD CONSTRAINT volunteer_phone_uk UNIQUE ( phone_number );

ALTER TABLE volunteer ADD CONSTRAINT volunteer_email_uk UNIQUE ( email );

ALTER TABLE observation
    ADD CONSTRAINT appointment_observation_fk FOREIGN KEY ( appointment_id )
        REFERENCES appointment ( appointment_id ) ON DELETE CASCADE;

ALTER TABLE requirement
    ADD CONSTRAINT department_requirement_fk FOREIGN KEY ( department_id )
        REFERENCES department ( department_id ) ON DELETE CASCADE;

ALTER TABLE volunteer
    ADD CONSTRAINT department_volunteer_fk FOREIGN KEY ( department_id )
        REFERENCES department ( department_id ) ON DELETE CASCADE;

ALTER TABLE requirement
    ADD CONSTRAINT event_requirement_fk FOREIGN KEY ( event_id )
        REFERENCES event ( event_id ) ON DELETE CASCADE;

ALTER TABLE event
    ADD CONSTRAINT location_event_fk FOREIGN KEY ( location_id )
        REFERENCES location ( location_id ) ON DELETE CASCADE;  
  
ALTER TABLE appointment
    ADD CONSTRAINT requirement_appointment_fk FOREIGN KEY ( requirement_id )
        REFERENCES requirement ( requirement_id ) ON DELETE CASCADE;  
   
ALTER TABLE appointment
    ADD CONSTRAINT volunteer_appointment_fk FOREIGN KEY ( volunteer_id )
        REFERENCES volunteer ( volunteer_id ) ON DELETE CASCADE;


CREATE SEQUENCE appointment_appointment_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER appointment_appointment_id_trg BEFORE
    INSERT ON appointment
    FOR EACH ROW
    WHEN ( new.appointment_id IS NULL )
BEGIN
    :new.appointment_id := appointment_appointment_id_seq.nextval;
END;
/

CREATE SEQUENCE department_department_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER department_department_id_trg BEFORE
    INSERT ON department
    FOR EACH ROW
    WHEN ( new.department_id IS NULL )
BEGIN
    :new.department_id := department_department_id_seq.nextval;
END;
/

CREATE SEQUENCE event_event_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER event_event_id_trg BEFORE
    INSERT ON event
    FOR EACH ROW
    WHEN ( new.event_id IS NULL )
BEGIN
    :new.event_id := event_event_id_seq.nextval;
END;
/

CREATE SEQUENCE location_location_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER location_location_id_trg BEFORE
    INSERT ON location
    FOR EACH ROW
    WHEN ( new.location_id IS NULL )
BEGIN
    :new.location_id := location_location_id_seq.nextval;
END;
/

CREATE SEQUENCE observation_observation_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER observation_observation_id_trg BEFORE
    INSERT ON observation
    FOR EACH ROW
    WHEN ( new.observation_id IS NULL )
BEGIN
    :new.observation_id := observation_observation_id_seq.nextval;
END;
/

CREATE SEQUENCE requirement_requirement_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER requirement_requirement_id_trg BEFORE
    INSERT ON requirement
    FOR EACH ROW
    WHEN ( new.requirement_id IS NULL )
BEGIN
    :new.requirement_id := requirement_requirement_id_seq.nextval;
END;
/

CREATE SEQUENCE volunteer_volunteer_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER volunteer_volunteer_id_trg BEFORE
    INSERT ON volunteer
    FOR EACH ROW
    WHEN ( new.volunteer_id IS NULL )
BEGIN
    :new.volunteer_id := volunteer_volunteer_id_seq.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             1
-- ALTER TABLE                             31
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           7
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          7
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0


